# Changed publish directory for Github Pages
publishDir = "docs"

# Page settings
baseurl = "https://dwhacademy.com/"
title = "DWH Academy"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Grzegorz Swierniak"
  description = "main author_x"
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "DWH Academy"
    home = "Home"
    work = "DWH best practices"
    services = "Projects"
    about = "About"
    contact = "Contact"
    testimonials = "Blog"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Why Reinvent the Wheel: there are DWH patterns that work"
    subtitle = 'Through our professional careers, we saw many common mistakes that different organizations were making when building data warehouses and we are truly sick of seeing how they are repeated again and again. The goal of this project is to share our proven patterns and good practices that we developed over the last 15 years.'
    subtitle2 = ''
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Agile"
    description = "We believe that a successful data warehouse can be built in Agile - we have proven that it is really possible!"
    url = "https://posts.dwhacademy.com"
    button = "Read more"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Proven Design"
    description = "Stage layer, Core layer, and Business Semantic layer - these are 3 gold pillars that will establish every successful data warehouse."
    url = "https://posts.dwhacademy.com/proven-design/"
    button = "Read more"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Cross Functionality"
    description = "Separation of roles leads to many challenges, therefore, make sure each of your team members can play someone's else role."
    url = "https://posts.dwhacademy.com"
    button = "Read more?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # DWH best practices
  [params.work]
    enable = true
    title = "DWH best practices"
    description = "''Using reason without applying it to experience only leads to theoretical illusions. Ideas derived from real world experiences lead to acquisition of knowledge, and the accumulation of time-tested principles leads to wisdom.'' ― Kilroy J. Oldster"
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Transparency"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Business orientation"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Multiple layers"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Agile was of working"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Abstraction"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Pilot first"
      subtitle = "Design"

  # Blog section
  [params.testimonials]
    enable = true
    title = "Blog"
    description = "We love talking about datawarehousing, below you can find articles that we posted on our <a href='https://posts.dwhacademy.com/' target='_blank'>Blog</a>."

    [[params.testimonials.item]]
      quote = "&ldquo;There is an unlimited number of ways how to build a data warehouse. Few of them work and some of the few can even survive in the long term. In this post, we are going to describe the high-level design of the typical successful DWH in the long term. &rdquo;"
      person = 'Lubomir Kamensky <a href="https://posts.dwhacademy.com/proven-design/" target="_blank">Read more</a> <span class="subtext">DWH Concultant</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Projects section
  [params.services]
    enable = true
    title = "Projects"
    description = "“Education without application is just entertainment.” -- Tim Sanders. Here are the white papers that we wrote based on our real projects"

    [[params.services.item]]
      title = "Nordea"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Merck Sharpe and Dhome"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Franklin Templeton Investment"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "DHL"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About us"
    description = "Our team represent a core strength of DWH – our professionals have owned their own businesses. We have learned from our own successes and mistakes, which allows us to share our proven patterns to successfully build and maintain DWH in your organization."

    [[params.about.item]]
      name = "Lubomir Kamensky"
      position = "DWH Consultant"
      description = "15 years of experience in building enterprise data warehouses in Logistics, Telco, Banking and Pharma. Lubo has a strong passion to observe, connect and make things work. Using the power of abstraction to utilize the unexpected patterns."
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-linkedin", "https://www.linkedin.com/in/lubomirkamensky/"]
      ]

    [[params.about.item]]
      name = "Grzegorz Swierniak"
      position = "Data Modeler"
      description = "His pragmatic approach leads to functional and robust solutions that work. He played multiple roles in DWH projects, so he gets different perspectives and angles in order to clearly define problems and solve them."
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-linkedin", "https://www.linkedin.com/in/grzegorz-%C5%9Bwierniak-53145078/"]
      ]
     

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 23
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 189349
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 14
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Feel free to contact us if you want to share your thoughts about our project - DWH Academy."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Pavla Svandy ze Semcic 1073, Prague 150 00 Smichov, <br> Czech Republic"],
        ["icon-envelope", "contact-dwhacademy@gmail.com"],
        ["icon-globe", '<a href="http://dwhacademy/" target="_blank">dwhacademy.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "https://youtube.com"]
      ]
