# Changed publish directory for Github Pages
publishDir = "docs"

# Page settings
baseurl = "https://dwhacademy.com/"
title = "DWH Academy"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Grzegorz Swierniak"
  description = "main author"
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "<img src='images/dwhacademy4.png' height='69px' STYLE='position:absolute; TOP:0px'>"
    home = "Home"
    services = "Core principles"
    work = "Projects"
    testimonials = "Blog"
    about = "About"
    contact = "Contact"
    

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Why Reinvent the Wheel"
    subtitle = 'Through our careers, we saw mistakes that many organizations were making when building data warehouses and we are truly sick of seeing how the same mistakes are repeated again and again. The goal of this project is to share our proven patterns and good practices we developed over the last 15 years.'
    subtitle2 = 'There are DWH patterns which already work'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Busines Orientation"
    description = "Real success of a data warehouse is defined by number of users who use it on a daily basis, so do not forget to always put their needs in the first place."
    url = "https://posts.dwhacademy.com/business-orientation"
    button = "Read more"
    icon = "icon-anchor"
    img = "img_10.jpg"

  [[params.intro.item]]
    title = "Agile"
    description = "It is easier to build successful data warehouse in Agile with cross-functional team players. Make sure each of your team members can play someone's else role"
    url = "https://posts.dwhacademy.com"
    button = "Read more"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Proven Design"
    description = "Straightforward Stage layer, normalized Integrated layer, and business oriented, dimensional Access layer - these are 3 gold pillars of successful data warehouse."
    url = "https://posts.dwhacademy.com/proven-design/"
    button = "Read more"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"

  # Core principles
  [params.services]
    enable = true
    title = "Core principles"
    description = "''Using reason without applying it to experience only leads to theoretical illusions. Ideas derived from real world experiences lead to acquisition of knowledge, and the accumulation of time-tested principles leads to wisdom.'' ― Kilroy J. Oldster"
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'


    [[params.services.item]]
      title = "Code Under Control"
      description = "Version control system is an essential tool for DWH projects, tracking changes in the code during development. GIT is a great choice due to the best fit into agile integration."
      icon = "icon-code"

    [[params.services.item]]
      title = "Separation of Concerns"
      description = "This principle is applicable recursively starting with DWH layers, going down to data models, entities, attributes. Experiences show that Separation of concerns makes DWH solution maintainable in the long term. "
      icon = "icon-layers2"

      [[params.services.item]]
      title = "End-to-end Transaparency"
      description = "Clear and well-commented code and configuration files, descriptive documentation of the whole data flow. No black boxes and magician features. The best code is not the shortest but the most self-descriptive one."      
      icon = "icon-monitor"

    [[params.services.item]]
      title = "Automation"
      description = "Anything what can be automated, has to be automated. Start with packaging, deployment and testing. Analyse all repeating activities and assess which really need to be manual."
      icon = "icon-video2"

    [[params.services.item]]
      title = "Symplicity"
      description = "There are several traditional approaches helping to keep things simple like Refactoring, YAGNI, Single responsibility, DRY. Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away (Antoine de Saint-Exupery)."
      icon = "icon-code"


 # Projects section
  [params.work]
    enable = true
    title = "Projects"
    description = "“Education without application is just entertainment.” -- Tim Sanders. Here are the white papers that we wrote based on our real projects"

    [[params.work.row]]
      img = "pharma.JPG"
      alt = "Image2"
      title = "Merck Sharpe and Dhome"
      subtitle = "Enteprise Data Warehouse Pharma"

    [[params.work.row]]
      img = "logistics.JPG"
      alt = "Image2"
      title = "DHL"
      subtitle = "Enteprise Data Warehouse Logistics"

    [[params.work.row]]
      img = "telco1.JPG"
      alt = "Image3"
      title = "Kyivstar GSM"
      subtitle = "Enteprise Data Warehouse Telco"

    [[params.work.row]]
      img = "fin_srvcs.JPG"
      alt = "Image4"
      title = "Franklin Templeton Investment"
      subtitle = "Enterprise Performance Mgmt Financial Svcs"

    [[params.work.row]]
      img = "telco2.JPG"
      alt = "Image5"
      title = "Telefonica"
      subtitle = "Enterprise Data Warehouse Telco"

    [[params.work.row]]
      img = "bank.JPG"
      alt = "Image6"
      title = "Nordea"
      subtitle = "Enterprise Data Warehouse Banking"

  # Blog section
  [params.testimonials]
    enable = true
    title = "Blog"
    description = "We love sharing our ideas about datawarehousing, below you can find some of the articles that we posted on our <a href='https://posts.dwhacademy.com/' target='_blank'>Blog</a>."

    [[params.testimonials.item]]
      quote = "&ldquo;When DWH accumulates unorganized data it tends to experience some kind of Turbo Effect in the entropy increase. The main motivation to start the project DWH Academy was to share the patterns and tools which work to build a successful Data warehouse. &rdquo;"
      person = 'Lubomir Kamensky <a href="https://posts.dwhacademy.com/entropy-of-dwh/" target="_blank">Read more</a> <span class="subtext">DWH Consultant</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;There is an unlimited number of ways how to build a data warehouse. Few of them work and some of the few can even survive in the long term. In this post, we are going to describe the high-level design of the typical successful DWH in the long term. &rdquo;"
      person = 'Lubomir Kamensky <a href="https://posts.dwhacademy.com/proven-design/" target="_blank">Read more</a> <span class="subtext">DWH Consultant</span>'
      img = "person1.jpg"
      alt = "Person1"

    

  # About section
  [params.about]
    enable = true
    title = "About us"
    description = "We are the alliance of DWH veterans, professionals who have owned their own businesses. We have learned already from our own successes and mistakes, which allows us to share our proven patterns to help you successfully build and maintain DWH in your organization."

    [[params.about.item]]
      name = "Lubomir Kamensky"
      position = "DWH Consultant"
      description = "15 years of experience in building enterprise data warehouses in Logistics, Telco, Banking, and Pharma. Lubo has a strong passion to observe, connect and make things work. Using the power of abstraction to utilize unexpected patterns."
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-linkedin", "https://www.linkedin.com/in/lubomirkamensky/"]
      ]

    [[params.about.item]]
      name = "Grzegorz Swierniak"
      position = "DWH Consultant"
      description = "8 years of experience in Business Intelligence. His pragmatic approach leads to functional and robust solutions that work. He played multiple roles in DWH projects, so he gets different perspectives and angles in order to clearly define problems and solve them."
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-linkedin", "https://www.linkedin.com/in/grzegorz-%C5%9Bwierniak-53145078/"]
      ]
     

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 23
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 189349
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 14
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Feel free to contact us if you want to share your thoughts about our project - DWH Academy."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Pavla Svandy ze Semcic 1073, Prague 150 00 Smichov, <br> Czech Republic"],
        ["icon-envelope", "contact-dwhacademy@gmail.com"],
        ["icon-globe", '<a href="http://dwhacademy/" target="_blank">dwhacademy.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = 'Made with [Hugo](https://gohugo.io/). Themed by [Elate Free HTML5](http://freehtml5.co). Deployed to [GitHub](https://github.com/).<br>&copy;DWH Academy 2019'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "https://youtube.com"]
      ]

